version: 2

updates:
  - package-ecosystem: "pip"
    directory: "app/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  
