domains: "scene.knilab.com"
# static_bucket: "media.knilab.com"
service_exec: "{{ virtualenv}}/bin/gunicorn -b :{{ service_port }} --reload --workers 3 {{ wsgi_application }}"

init_env_stg:
  #STATIC_MEDIA_URL: "https://media.knilab.com/{{ project_name }}"
  STATIC_MEDIA_URL: "/static/dist"
  SCENEVR_DIST_ROOT_URL: "https://cdn.knightlab.com/libs/scenevr/dev"

# Note that env vars set in the upstart config will also be set when using the
# modified manage.py file for db migration and custom management commands
init_env: "{{ init_env_common|combine(init_env_stg) }}"
