- hosts: "{{ env }}"
  vars_files:
    - "{{ config_dir }}/config.common.yml"
    - "{{ config_dir }}/config.{{ env }}.yml"
    - "{{ vault }}"
  gather_facts: false

  roles:
    - role: knightlab

  tasks:
    - name: Copy scenevr secrets file
      become: yes
      template:
        src: "templates/scenevr_client_secret.json"
        dest: "/home/apps/sites/scenevr-author/app/server/scenevr_client_secret.json"

    #- name: "npm install"
    #  ansible.builtin.command: npm install .
    #  args:
    #    chdir: "{{ deploy_dir }}"

    #- name: "Install static dependencies"
    #  ansible.builtin.command: "npm install"
    #  args:
    #    chdir: "{{ deploy_dir }}"
    #- name: "Build static"
    #  ansible.builtin.command: "npm run build"
    #  args:
    #    chdir: "{{ deploy_dir }}"

